spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:customerdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Arshi123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084

logging:
  level:
    root: INFO
