

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/peterfink
    username: postgres
    password: SummercometPG
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
    com.zaxxer.hikari: DEBUG
    org.hibernate.engine.jdbc.connections: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka