spring:
  application:
    name: gps-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
      # uri: mongodb+srv://<username>:<password>@<cluster-url>/gpsdb

    redis:
      host: localhost
      port: 6379
      # timeout: 6000

server:
  port: 8081

logging:
  level:
    org.springframework: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
